title: Andr√©s Ingelmo Personal Portfolio
description: Spotlight for personal projects.
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
